//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterAspNetMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonement
    {
        public int a_id { get; set; }
        public int client_id { get; set; }
        public System.DateTime date_begin { get; set; }
        public int service_id { get; set; }
        public System.DateTime date_end { get; set; }
        public int a_count { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
